name: stylus
version: 0.1.1
author: Wilker Lucio <wilkerlucio@gmail.com>
description: Stylus CLI wrapper for Dart
homepage: https://github.com/wilkerlucio/dart-stylus
dependencies:
  editor_build: '>=0.0.4 <=1.0.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
